//Yemek Resimleri
import sariMercimekCorbasiImage from "../assets/yemek/corba/sari-mercimek-corba.jpeg"
import ispanakliSariMercimekCorbasiImage from "../assets/yemek/corba/ispanakli-sari-mercimek-corba.jpg"
import kirmiziMercimekCorbasiImage from "../assets/yemek/corba/kirmizi-mercimek-corba.jpg"
import sosisliKirmiziMercimekCorbasiImage from "../assets/yemek/corba/sosisli-mercimek.jpg"
import nohutluPilavImage from "../assets/yemek/pilav/nohutlu-pilav.jpg"
import bademliPilavImage from "../assets/yemek/pilav/bademli-pilav.jpg"
import domatesliPilavImage from "../assets/yemek/pilav/domatesli-pilav.jpg"
import sebzeliBulgurPilaviImage from "../assets/yemek/pilav/sebzeli-bulgur-pilavi.jpg"
import akasyaPilaviImage from "../assets/yemek/pilav/akasya-pilavi.jpg"
import etliBulgurImage from "../assets/yemek/pilav/etli-bulgur-pilavi.jpeg"
import kuruFasulyeImage from "../assets/yemek/fasulye/kuru-fasulye.jpg"
import etliKuruFasulyeImage from "../assets/yemek/fasulye/etli-kuru-fasulye.jpg"
import sekerFasulyeImage from "../assets/yemek/fasulye/seker-fasulye.jpg"
import beyazNohutImage from "../assets/yemek/nohut/beyaz-nohut.jpg"
import tavukluBeyazNohutImage from "../assets/yemek/nohut/tavuklu-nohut.jpg"
import kocbasiNohutImage from "../assets/yemek/nohut/kocbasi-nohut.jpg"
import nohutGuvecImage from "../assets/yemek/nohut/guvec-nohut.jpg"
import yesilMercimekImage from "../assets/yemek/yesilMercimek/yesil-mercimek.jpg"
import yesilMercimekliIspanakImage from "../assets/yemek/yesilMercimek/ispanak-yesil-mercimek.jpg"
import yesilMercimekKoftesiImage from "../assets/yemek/yesilMercimek/kofte-yesil-mercimek.jpg"
import barbunyaPilakiImage from "../assets/yemek/barbunya/barbunya-pilaki.jpg"
import kirazBarbunyaImage from "../assets/yemek/barbunya/barbunya-kiraz.jpg"
import bulgurluKofteImage from "../assets/yemek/bulgurKoftesi.jpg"
import yaprakSarmaImage from "../assets/yemek/yaprak-sarma.jpg"
import yalanciCigKofteImage from "../assets/yemek/cigKofte.jpg"
import asureImage from "../assets/yemek/asure.jpg"


export const recipes = [
    {
        id: 1,
        title: "Sarı Mercimek Çorbası",
        type: "Çorbalar",
        href: "",
        ingredients: [
            "sari1",
            "sari2",
            "sari3",
            "sari4",
            "sari5",
            "sari6",
            "sari7",
            "sari8",
            "sari9",
            "sari10"
        ],
        instructions: [
            "sariTarif1",
            "sariTarif2",
            "sariTarif3",
            "sariTarif4",
            "sariTarif5",
            "sariTarif6",
            "sariTarif7",
            "sariTarif8",
            "sariTarif9",
        ],
        image: sariMercimekCorbasiImage
    },
    {
        id: 2,
        title: "Ispanaklı Sarı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            "ispanak1",
            "ispanak2",
            "ispanak3",
            "ispanak4",
            "ispanak5",
            "ispanak6",
            "ispanak7",
            "ispanak8",
            "ispanak9",
            "ispanak10",
            "ispanak11"
        ],
        instructions: [
            "ispanakTarif1",
            "ispanakTarif2",
            "ispanakTarif3",
            "ispanakTarif4",
            "ispanakTarif5",
            "ispanakTarif6",
            "ispanakTarif7",
            "ispanakTarif8",
            "ispanakTarif9",
            "ispanakTarif10",
        ],
        image: ispanakliSariMercimekCorbasiImage
    },
    {
        id: 3,
        title: "Kırmızı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            "kirmizi1",
            "kirmizi2",
            "kirmizi3",
            "kirmizi4",
            "kirmizi5",
            "kirmizi6",
            "kirmizi7",
            "kirmizi8",
            "kirmizi9",
            "kirmizi10",
            "kirmizi11",
        ],
        instructions: [
            "kirmiziTarif1",
            "kirmiziTarif2",
            "kirmiziTarif3",
            "kirmiziTarif4",
            "kirmiziTarif5",
            "kirmiziTarif6",
            "kirmiziTarif7",
            "kirmiziTarif8",
            "kirmiziTarif9",
            "kirmiziTarif10",
        ],
        image: kirmiziMercimekCorbasiImage
    },
    {
        id: 4,
        title: "Sosisli Kırmızı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            "sosisli1",
            "sosisli2",
            "sosisli3",
            "sosisli4",
            "sosisli5",
            "sosisli6",
            "sosisli7",
            "sosisli8",
            "sosisli9",
            "sosisli10",
            "sosisli11",
            "sosisli12",
        ],
        instructions: [
            "sosisliTarif1",
            "sosisliTarif2",
            "sosisliTarif3",
            "sosisliTarif4",
            "sosisliTarif5",
            "sosisliTarif6",
            "sosisliTarif7",
            "sosisliTarif8",
            "sosisliTarif9",
            "sosisliTarif10",
            "sosisliTarif11",
        ],
        image: sosisliKirmiziMercimekCorbasiImage
    },
    {
        id: 5,
        title: "Nohutlu Pilav",
        type: "Pilavlar",
        ingredients: [
            "nohutlu1",
            "nohutlu2",
            "nohutlu3",
            "nohutlu4",
            "nohutlu5",
            "nohutlu6",
            "nohutlu7",
        ],
        instructions: [
            "nohutluTarif1",
            "nohutluTarif2",
            "nohutluTarif3",
            "nohutluTarif4",
            "nohutluTarif5",
            "nohutluTarif6",
            "nohutluTarif7",
        ],
        image: nohutluPilavImage
    },
    {
        id: 6,
        title: "Bademli Pilav",
        type: "Pilavlar",
        ingredients: [
            "bademli1",
            "bademli2",
            "bademli3",
            "bademli4",
            "bademli5",
            "bademli6",
            "bademli7",
            "bademli8",
        ],
        instructions: [
            "bademliTarif1",
            "bademliTarif2",
            "bademliTarif3",
            "bademliTarif4",
            "bademliTarif5",
            "bademliTarif6",
            "bademliTarif7",
            "bademliTarif8",
        ],
        image: bademliPilavImage
    },
    {
        id: 7,
        title: "Domatesli Pilav",
        type: "Pilavlar",
        ingredients: [
            "domatesli1",
            "domatesli2",
            "domatesli3",
            "domatesli4",
            "domatesli5",
            "domatesli6",
            "domatesli7",
            "domatesli8",
        ],
        instructions: [
            "domatesliTarif1",
            "domatesliTarif2",
            "domatesliTarif3",
            "domatesliTarif4",
            "domatesliTarif5",
            "domatesliTarif6",
            "domatesliTarif7",
            "domatesliTarif8",
        ],
        image: domatesliPilavImage
    },
    {
        id: 8,
        title: "Sebzeli Bulgur Pilavı",
        type: "Pilavlar",
        ingredients: [
            "sebzeli1",
            "sebzeli2",
            "sebzeli3",
            "sebzeli4",
            "sebzeli5",
            "sebzeli6",
            "sebzeli7",
            "sebzeli8",
            "sebzeli9",
            "sebzeli10",
            "sebzeli11",
        ],
        instructions: [
            "sebzeliTarif1",
            "sebzeliTarif2",
            "sebzeliTarif3",
            "sebzeliTarif4",
            "sebzeliTarif5",
            "sebzeliTarif6",
            "sebzeliTarif7",
            "sebzeliTarif8",
            "sebzeliTarif9",
        ],
        image: sebzeliBulgurPilaviImage
    },
    {
        id: 9,
        title: "Akasya Pilavı",
        type: "Pilavlar",
        ingredients: [
            "akasya1",
            "akasya2",
            "akasya3",
            "akasya4",
            "akasya5",
            "akasya6",
            "akasya7",
            "akasya8",
            "akasya9",
            "akasya10",
            "akasya11",
        ],
        instructions: [
            "akasyaTarif1",
            "akasyaTarif2",
            "akasyaTarif3",
            "akasyaTarif4",
            "akasyaTarif5",
            "akasyaTarif6",
            "akasyaTarif7",
            "akasyaTarif8",
            "akasyaTarif9",
            "akasyaTarif10",
        ],
        image: akasyaPilaviImage
    },
    {
        id: 10,
        title: "Etli Bulgur Pilavı",
        type: "Pilavlar",
        ingredients: [
            "etli1",
            "etli2",
            "etli3",
            "etli4",
            "etli5",
            "etli6",
            "etli7",
            "etli8",
            "etli9",
            "etli10",
            "etli11",
        ],
        instructions: [
            "etliTarif1",
            "etliTarif2",
            "etliTarif3",
            "etliTarif4",
            "etliTarif5",
            "etliTarif6",
            "etliTarif7",
        ],
        image: etliBulgurImage
    },
    {
        id: 11,
        title: "Kuru Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            "kuru1",
            "kuru2",
            "kuru3",
            "kuru4",
            "kuru5",
            "kuru6",
            "kuru7",
            "kuru8",
            "kuru9",
        ],
        instructions: [
            "kuruTarif1",
            "kuruTarif2",
            "kuruTarif3",
            "kuruTarif4",
            "kuruTarif5",
            "kuruTarif6",
            "kuruTarif7",
            "kuruTarif8",
            "kuruTarif9",
        ],
        image: kuruFasulyeImage
    },
    {
        id: 12,
        title: "Etli Kuru Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            "etliKuru1",
            "etliKuru2",
            "etliKuru3",
            "etliKuru4",
            "etliKuru5",
            "etliKuru6",
            "etliKuru7",
            "etliKuru8",
            "etliKuru9",
        ],
        instructions: [
            "etliKuruTarif1",
            "etliKuruTarif2",
            "etliKuruTarif3",
            "etliKuruTarif4",
            "etliKuruTarif5",
            "etliKuruTarif6",
            "etliKuruTarif7",
            "etliKuruTarif8",
            "etliKuruTarif9",
        ],
        image: etliKuruFasulyeImage
    },
    {
        id: 13,
        title: "Güveçte Şeker Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            "guvec1",
            "guvec2",
            "guvec3",
            "guvec4",
            "guvec5",
            "guvec6",
            "guvec7",
            "guvec8",
        ],
        instructions: [
            "guvecTarif1",
            "guvecTarif2",
            "guvecTarif3",
            "guvecTarif4",
            "guvecTarif5",
            "guvecTarif6",
            "guvecTarif7",
            "guvecTarif8",
            "guvecTarif9",
        ],
        image: sekerFasulyeImage
    },
    {
        id: 14,
        title: "Beyaz Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            "beyaz1",
            "beyaz2",
            "beyaz3",
            "beyaz4",
            "beyaz",
            "beyaz61",
            "beyaz7",
            "beyaz8",
            "beyaz9",
        ],
        instructions: [
            "beyazTarif1",
            "beyazTarif2",
            "beyazTarif3",
            "beyazTarif4",
            "beyazTarif5",
            "beyazTarif6",
            "beyazTarif7",
            "beyazTarif8",
            "beyazTarif9",
            "beyazTarif10",
        ],
        image: beyazNohutImage
    },
    {
        id: 15,
        title: "Tavuklu Beyaz Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            "tavuklu1",
            "tavuklu2",
            "tavuklu3",
            "tavuklu4",
            "tavuklu5",
            "tavuklu6",
            "tavuklu7",
            "tavuklu8",
            "tavuklu9",
            "tavuklu10",
        ],
        instructions: [
            "tavukluTarif1",
            "tavukluTarif2",
            "tavukluTarif3",
            "tavukluTarif4",
            "tavukluTarif5",
            "tavukluTarif6",
            "tavukluTarif7",
            "tavukluTarif8",
            "tavukluTarif9",
            "tavukluTarif10",
            "tavukluTarif11",
        ],
        image: tavukluBeyazNohutImage
    },
    {
        id: 16,
        title: "Koçbaşı Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            "kocbasi1",
            "kocbasi2",
            "kocbasi3",
            "kocbasi4",
            "kocbasi5",
            "kocbasi6",
            "kocbasi7",
            "kocbasi8",
            "kocbasi9",
        ],
        instructions: [
            "kocbasiTarif1",
            "kocbasiTarif2",
            "kocbasiTarif3",
            "kocbasiTarif4",
            "kocbasiTarif5",
            "kocbasiTarif6",
            "kocbasiTarif7",
            "kocbasiTarif8",
            "kocbasiTarif9",
            "kocbasiTarif10",
        ],
        image: kocbasiNohutImage
    },
    {
        id: 17,
        title: "Nohut Güveç",
        type: "Nohut Yemekleri",
        ingredients: [
            "nohut1",
            "nohut2",
            "nohut3",
            "nohut4",
            "nohut5",
            "nohut6",
            "nohut7",
            "nohut8",
            "nohut9",
            "nohut10",
            "nohut11",
        ],
        instructions: [
            "nohutTarif1",
            "nohutTarif2",
            "nohutTarif3",
            "nohutTarif4",
            "nohutTarif5",
            "nohutTarif6",
            "nohutTarif7",
            "nohutTarif8",
            "nohutTarif9",
            "nohutTarif10",
            "nohutTarif11",
        ],
        image: nohutGuvecImage
    },
    {
        id: 18,
        title: "Yeşil Mercimek",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "yesilMercimek1",
            "yesilMercimek2",
            "yesilMercimek3",
            "yesilMercimek4",
            "yesilMercimek5",
            "yesilMercimek6",
            "yesilMercimek7",
            "yesilMercimek8",
            "yesilMercimek9",
            "yesilMercimek10",
            "yesilMercimek11",
        ],
        instructions: [
            "yesilMercimekTarif1",
            "yesilMercimekTarif2",
            "yesilMercimekTarif3",
            "yesilMercimekTarif4",
            "yesilMercimekTarif5",
            "yesilMercimekTarif6",
            "yesilMercimekTarif7",
            "yesilMercimekTarif8",
            "yesilMercimekTarif9",
            "yesilMercimekTarif10",
            "yesilMercimekTarif11",
        ],
        image: yesilMercimekImage
    },
    {
        id: 19,
        title: "Yeşil Mercimekli Ispanak",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "yesilIspanak1",
            "yesilIspanak2",
            "yesilIspanak3",
            "yesilIspanak4",
            "yesilIspanak5",
            "yesilIspanak6",
            "yesilIspanak7",
            "yesilIspanak8",
            "yesilIspanak9",
            "yesilIspanak10",
            "yesilIspanak11",
        ],
        instructions: [
            "yesilIspanakTarif1",
            "yesilIspanakTarif2",
            "yesilIspanakTarif3",
            "yesilIspanakTarif4",
            "yesilIspanakTarif5",
            "yesilIspanakTarif6",
            "yesilIspanakTarif7",
            "yesilIspanakTarif8",
            "yesilIspanakTarif9",
            "yesilIspanakTarif10",
            "yesilIspanakTarif11",
        ],
        image: yesilMercimekliIspanakImage
    },
    {
        id: 20,
        title: "Yeşil Mercimek Köftesi",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "yesilKofte1",
            "yesilKofte2",
            "yesilKofte3",
            "yesilKofte4",
            "yesilKofte5",
            "yesilKofte6",
            "yesilKofte7",
            "yesilKofte8",
            "yesilKofte9",
            "yesilKofte10",
            "yesilKofte11",
            "yesilKofte12",
            "yesilKofte13",
            "yesilKofte14",
            "yesilKofte15",
        ],
        instructions: [
            "yesilKofteTarif1",
            "yesilKofteTarif2",
            "yesilKofteTarif3",
            "yesilKofteTarif4",
            "yesilKofteTarif5",
            "yesilKofteTarif6",
            "yesilKofteTarif7",
            "yesilKofteTarif8",
            "yesilKofteTarif9",
            "yesilKofteTarif10",
            "yesilKofteTarif11",
        ],
        image: yesilMercimekKoftesiImage
    },
    {
        id: 21,
        title: "Barbunya Pilaki",
        type: "Barbunya Yemekleri",
        ingredients: [
            "barbunya1",
            "barbunya2",
            "barbunya3",
            "barbunya4",
            "barbunya5",
            "barbunya6",
            "barbunya7",
            "barbunya8",
            "barbunya9",
            "barbunya10",
            "barbunya11",
            "barbunya12",
            "barbunya13",
        ],
        instructions: [
            "barbunyaTarif1",
            "barbunyaTarif2",
            "barbunyaTarif3",
            "barbunyaTarif4",
            "barbunyaTarif5",
            "barbunyaTarif6",
            "barbunyaTarif7",
            "barbunyaTarif8",
            "barbunyaTarif9",
        ],
        image: barbunyaPilakiImage
    },
    {
        id: 22,
        title: "Kiraz Barbunya",
        type: "Barbunya Yemekleri",
        ingredients: [
            "kiraz1",
            "kiraz2",
            "kiraz3",
            "kiraz4",
            "kiraz5",
            "kiraz6",
            "kiraz7",
            "kiraz8",
            "kiraz9",
            "kiraz10",
            "kiraz11",
            "kiraz12",
            "kiraz13",
        ],
        instructions: [
            "kirazTarif1",
            "kirazTarif2",
            "kirazTarif3",
            "kirazTarif4",
            "kirazTarif5",
            "kirazTarif6",
            "kirazTarif7",
            "kirazTarif8",
            "kirazTarif9",
        ],
        image: kirazBarbunyaImage
    },
    {
        id: 23,
        title: "Bulgurlu Köfte",
        type: "Diğer Yemekler",
        ingredients: [
            "bulgurlu1",
            "bulgurlu2",
            "bulgurlu3",
            "bulgurlu4",
            "bulgurlu5",
            "bulgurlu6",
            "bulgurlu7",
            "bulgurlu8",
            "bulgurlu9",
            "bulgurlu10",
            "bulgurlu11",
            "bulgurlu12",
        ],
        instructions: [
            "bulgurluTarif1",
            "bulgurluTarif2",
            "bulgurluTarif3",
            "bulgurluTarif4",
            "bulgurluTarif5",
            "bulgurluTarif6",
        ],
        image: bulgurluKofteImage
    },
    {
        id: 24,
        title: "Yaprak Sarma",
        type: "Diğer Yemekler",
        ingredients: [
            "yaprak1",
            "yaprak2",
            "yaprak3",
            "yaprak4",
            "yaprak5",
            "yaprak6",
            "yaprak7",
            "yaprak8",
            "yaprak9",
            "yaprak10",
            "yaprak11",
            "yaprak12",
            "yaprak13",
        ],
        instructions: [
            "yaprakTarif1",
            "yaprakTarif2",
            "yaprakTarif3",
            "yaprakTarif4",
            "yaprakTarif5",
            "yaprakTarif6",
            "yaprakTarif7",
            "yaprakTarif8",
        ],
        image: yaprakSarmaImage
    },
    {
        id: 25,
        title: "Yalancı Çiğ Köfte",
        type: "Diğer Yemekler",
        ingredients: [
            "yalanci1",
            "yalanci2",
            "yalanci3",
            "yalanci4",
            "yalanci5",
            "yalanci6",
            "yalanci7",
            "yalanci8",
            "yalanci9",
            "yalanci10",
            "yalanci11",
            "yalanci12",
            "yalanci13",
            "yalanci14",
            "yalanci15",
            "yalanci16",
        ],
        instructions: [
            "yalanciTarif1",
            "yalanciTarif2",
            "yalanciTarif3",
            "yalanciTarif4",
            "yalanciTarif5",
            "yalanciTarif6",
        ],
        image: yalanciCigKofteImage
    },
    {
        id: 26,
        title: "Aşure",
        type: "Diğer Yemekler",
        ingredients: [
            "asure1",
            "asure2",
            "asure3",
            "asure4",
            "asure5",
            "asure6",
            "asure7",
            "asure8",
            "asure9",
            "asure10",
            "asure11",
            "asure12",
            "asure13",
            "asure14",
            "asure15",
        ],
        instructions: [
            "asureTarif1",
            "asureTarif2",
            "asureTarif3",
            "asureTarif4",
            "asureTarif5",
            "asureTarif6",
            "asureTarif7",
            "asureTarif8",
            "asureTarif9",
            "asureTarif10",
        ],
        image: asureImage
    }
]

export const categories = [
    {
        id: 1,
        name: "Çorbalar",
        image: sariMercimekCorbasiImage
    },
    {
        id: 2,
        name: "Pilavlar",
        image: domatesliPilavImage
    },
    {
        id: 3,
        name: "Fasulye Yemekleri",
        image: kuruFasulyeImage
    },
    {
        id: 4,
        name: "Nohut Yemekleri",
        image: nohutGuvecImage
    },
    {
        id: 5,
        name: "Yeşil Mercimek Yemekleri",
        image: yesilMercimekImage
    },
    {
        id: 6,
        name: "Barbunya Yemekleri",
        image: barbunyaPilakiImage
    },
    {
        id: 7,
        name: "Diğer Yemekler",
        image: asureImage
    }
]