//Yemek Resimleri
import sariMercimekCorbasiImage from "../assets/yemek/corba/sari-mercimek-corba.jpeg"
import ispanakliSariMercimekCorbasiImage from "../assets/yemek/corba/ispanakli-sari-mercimek-corba.jpg"
import kirmiziMercimekCorbasiImage from "../assets/yemek/corba/kirmizi-mercimek-corba.jpg"
import sosisliKirmiziMercimekCorbasiImage from "../assets/yemek/corba/sosisli-mercimek.jpg"
import nohutluPilavImage from "../assets/yemek/pilav/nohutlu-pilav.jpg"
import bademliPilavImage from "../assets/yemek/pilav/bademli-pilav.jpg"
import domatesliPilavImage from "../assets/yemek/pilav/domatesli-pilav.jpg"
import sebzeliBulgurPilaviImage from "../assets/yemek/pilav/sebzeli-bulgur-pilavi.jpg"
import akasyaPilaviImage from "../assets/yemek/pilav/akasya-pilavi.jpg"
import etliBulgurImage from "../assets/yemek/pilav/etli-bulgur-pilavi.jpeg"
import kuruFasulyeImage from "../assets/yemek/fasulye/kuru-fasulye.jpg"
import etliKuruFasulyeImage from "../assets/yemek/fasulye/etli-kuru-fasulye.jpg"
import sekerFasulyeImage from "../assets/yemek/fasulye/seker-fasulye.jpg"
import beyazNohutImage from "../assets/yemek/nohut/beyaz-nohut.jpg"
import tavukluBeyazNohutImage from "../assets/yemek/nohut/tavuklu-nohut.jpg"
import kocbasiNohutImage from "../assets/yemek/nohut/kocbasi-nohut.jpg"
import nohutGuvecImage from "../assets/yemek/nohut/guvec-nohut.jpg"
import yesilMercimekImage from "../assets/yemek/yesilMercimek/yesil-mercimek.jpg"
import yesilMercimekliIspanakImage from "../assets/yemek/yesilMercimek/ispanak-yesil-mercimek.jpg"
import yesilMercimekKoftesiImage from "../assets/yemek/yesilMercimek/kofte-yesil-mercimek.jpg"
import barbunyaPilakiImage from "../assets/yemek/barbunya/barbunya-pilaki.jpg"
import kirazBarbunyaImage from "../assets/yemek/barbunya/barbunya-kiraz.jpg"
import bulgurluKofteImage from "../assets/yemek/bulgurKoftesi.jpg"
import yaprakSarmaImage from "../assets/yemek/yaprak-sarma.jpg"
import yalanciCigKofteImage from "../assets/yemek/cigKofte.jpg"
import asureImage from "../assets/yemek/asure.jpg"


export const recipes = [
    {
        id: 1,
        title: "Sarı Mercimek Çorbası",
        type: "Çorbalar",
        href: "",
        ingredients: [
            // "1 su bardağı sarı mercimek",
            // "1 adet büyük soğan, doğranmış",
            // "1 adet havuç, doğranmış",
            // "1 adet patates, doğranmış",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz (damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "1 tatlı kaşığı kimyon",
            // "5 su bardağı su veya tavuk suyu",
            // "1 adet limon (servis için)",
            "sari1",
            "sari2",
            "sari3",
            "sari4",
            "sari5",
            "sari6",
            "sari7",
            "sari8",
            "sari9",
            "sari10"
        ],
        instructions: [
            "sariTarif1",
            "sariTarif2",
            "sariTarif3",
            "sariTarif4",
            "sariTarif5",
            "sariTarif6",
            "sariTarif7",
            "sariTarif8",
            "sariTarif9",
            // "Sarı mercimekleri yıkayıp süzün.",
            // "Bir tencereye sıvı yağı veya tereyağını ekleyin ve ısıtın. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Doğranmış havuç ve patatesleri ekleyin, birkaç dakika karıştırarak kavurun.",
            // "Yıkanmış sarı mercimekleri tencereye ekleyin ve karıştırın.",
            // "Tuz, karabiber ve kimyonu ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Çorba kaynamaya başladıktan sonra, ısıyı azaltın ve sebzeler tamamen yumuşayana kadar yaklaşık 20-25 dakika pişirin.",
            // "Pişen çorbayı blender veya el blendırı ile pürüzsüz bir kıvam alana kadar ezin. Eğer çorba çok koyu ise biraz daha su ekleyebilirsiniz.",
            // "Çorbayı tekrar ocağa alın ve bir taşım daha kaynatın. Tadını kontrol edip gerekirse tuz ve baharat ekleyin.",
            // "Sıcak olarak limon dilimleri ile servis yapın. Afiyet olsun!"
        ],
        image: sariMercimekCorbasiImage
    },
    {
        id: 2,
        title: "Ispanaklı Sarı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            // "1 su bardağı sarı mercimek",
            // "1 adet büyük soğan, doğranmış",
            // "1 adet havuç, doğranmış",
            // "1 adet patates, doğranmış",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz (damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "1 tatlı kaşığı kimyon",
            // "5 su bardağı su veya tavuk suyu",
            // "100 gram ıspanak, doğranmış",
            // "1 adet limon (servis için)"
            "ispanak1",
            "ispanak2",
            "ispanak3",
            "ispanak4",
            "ispanak5",
            "ispanak6",
            "ispanak7",
            "ispanak8",
            "ispanak9",
            "ispanak10",
            "ispanak11"
        ],
        instructions: [
            "ispanakTarif1",
            "ispanakTarif2",
            "ispanakTarif3",
            "ispanakTarif4",
            "ispanakTarif5",
            "ispanakTarif6",
            "ispanakTarif7",
            "ispanakTarif8",
            "ispanakTarif9",
            "ispanakTarif10",
            // "Sarı mercimekleri yıkayıp süzün.",
            // "Bir tencereye sıvı yağı veya tereyağını ekleyin ve ısıtın. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Doğranmış havuç ve patatesleri ekleyin, birkaç dakika karıştırarak kavurun.",
            // "Yıkanmış sarı mercimekleri tencereye ekleyin ve karıştırın.",
            // "Tuz, karabiber ve kimyonu ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Çorba kaynamaya başladıktan sonra, ısıyı azaltın ve sebzeler tamamen yumuşayana kadar yaklaşık 20-25 dakika pişirin.",
            // "Pişen çorbayı blender veya el blendırı ile pürüzsüz bir kıvam alana kadar ezin. Eğer çorba çok koyu ise biraz daha su ekleyebilirsiniz.",
            // "Doğranmış ıspanakları ekleyin ve birkaç dakika daha pişirin, ıspanaklar yumuşayana kadar.",
            // "Çorbayı tekrar ocağa alın ve bir taşım daha kaynatın. Tadını kontrol edip gerekirse tuz ve baharat ekleyin.",
            // "Sıcak olarak limon dilimleri ile servis yapın. Afiyet olsun!"
        ],
        image: ispanakliSariMercimekCorbasiImage
    },
    {
        id: 3,
        title: "Kırmızı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            // "1 su bardağı kırmızı mercimek",
            // "1 adet büyük soğan, doğranmış",
            // "1 adet havuç, doğranmış",
            // "1 adet patates, doğranmış",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 yemek kaşığı domates salçası",
            // "1 tatlı kaşığı tuz (damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "1 tatlı kaşığı kimyon",
            // "6 su bardağı su veya tavuk suyu",
            // "1 adet limon (servis için)",
            "kirmizi1",
            "kirmizi2",
            "kirmizi3",
            "kirmizi4",
            "kirmizi5",
            "kirmizi6",
            "kirmizi7",
            "kirmizi8",
            "kirmizi9",
            "kirmizi10",
            "kirmizi11",
        ],
        instructions: [
            // "Kırmızı mercimekleri yıkayıp süzün.",
            // "Bir tencereye sıvı yağı veya tereyağını ekleyin ve ısıtın. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Doğranmış havuç ve patatesleri ekleyin, birkaç dakika karıştırarak kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurun.",
            // "Yıkanmış kırmızı mercimekleri tencereye ekleyin ve karıştırın.",
            // "Tuz, karabiber ve kimyonu ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Çorba kaynamaya başladıktan sonra, ısıyı azaltın ve sebzeler tamamen yumuşayana kadar yaklaşık 20-25 dakika pişirin.",
            // "Pişen çorbayı blender veya el blendırı ile pürüzsüz bir kıvam alana kadar ezin. Eğer çorba çok koyu ise biraz daha su ekleyebilirsiniz.",
            // "Çorbayı tekrar ocağa alın ve bir taşım daha kaynatın. Tadını kontrol edip gerekirse tuz ve baharat ekleyin.",
            // "Sıcak olarak limon dilimleri ile servis yapın. Afiyet olsun!",
            "kirmiziTarif1",
            "kirmiziTarif2",
            "kirmiziTarif3",
            "kirmiziTarif4",
            "kirmiziTarif5",
            "kirmiziTarif6",
            "kirmiziTarif7",
            "kirmiziTarif8",
            "kirmiziTarif9",
            "kirmiziTarif10",
        ],
        image: kirmiziMercimekCorbasiImage
    },
    {
        id: 4,
        title: "Sosisli Kırmızı Mercimek Çorbası",
        type: "Çorbalar",
        ingredients: [
            // "1 su bardağı kırmızı mercimek",
            // "1 adet büyük soğan, doğranmış",
            // "1 adet havuç, doğranmış",
            // "1 adet patates, doğranmış",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 yemek kaşığı domates salçası",
            // "3 adet sosis, dilimlenmiş",
            // "1 tatlı kaşığı tuz (damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "1 tatlı kaşığı kimyon",
            // "6 su bardağı su veya tavuk suyu",
            // "1 adet limon (servis için)",
            "sosisli1",
            "sosisli2",
            "sosisli3",
            "sosisli4",
            "sosisli5",
            "sosisli6",
            "sosisli7",
            "sosisli8",
            "sosisli9",
            "sosisli10",
            "sosisli11",
            "sosisli12",
        ],
        instructions: [
            // "Kırmızı mercimekleri yıkayıp süzün.",
            // "Bir tencereye sıvı yağı veya tereyağını ekleyin ve ısıtın. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Doğranmış havuç ve patatesleri ekleyin, birkaç dakika karıştırarak kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurun.",
            // "Dilimlenmiş sosisleri ekleyin ve birkaç dakika kavurun.",
            // "Yıkanmış kırmızı mercimekleri tencereye ekleyin ve karıştırın.",
            // "Tuz, karabiber ve kimyonu ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Çorba kaynamaya başladıktan sonra, ısıyı azaltın ve sebzeler tamamen yumuşayana kadar yaklaşık 20-25 dakika pişirin.",
            // "Pişen çorbayı blender veya el blendırı ile pürüzsüz bir kıvam alana kadar ezin. Eğer çorba çok koyu ise biraz daha su ekleyebilirsiniz.",
            // "Çorbayı tekrar ocağa alın ve bir taşım daha kaynatın. Tadını kontrol edip gerekirse tuz ve baharat ekleyin.",
            // "Sıcak olarak limon dilimleri ile servis yapın. Afiyet olsun!",
            "sosisliTarif1",
            "sosisliTarif2",
            "sosisliTarif3",
            "sosisliTarif4",
            "sosisliTarif5",
            "sosisliTarif6",
            "sosisliTarif7",
            "sosisliTarif8",
            "sosisliTarif9",
            "sosisliTarif10",
            "sosisliTarif11",
        ],
        image: sosisliKirmiziMercimekCorbasiImage
    },
    {
        id: 5,
        title: "Nohutlu Pilav",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı pirinç",
            // "1 su bardağı haşlanmış nohut",
            // "2 yemek kaşığı tereyağı",
            // "2 yemek kaşığı sıvı yağ",
            // "3 su bardağı su veya tavuk suyu",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber"
            "nohutlu1",
            "nohutlu2",
            "nohutlu3",
            "nohutlu4",
            "nohutlu5",
            "nohutlu6",
            "nohutlu7",
        ],
        instructions: [
            // "Pirinçleri tuzlu ılık suda yaklaşık 20-30 dakika bekletin. Daha sonra bol su ile yıkayıp süzün.",
            // "Bir tencereye tereyağını ve sıvı yağı ekleyin. Yağlar eridikten sonra pirinçleri ekleyin ve pirinçler şeffaflaşana kadar kavurun.",
            // "Haşlanmış nohutları ekleyin ve karıştırın.",
            // "Tuz ve karabiberi ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Kaynadıktan sonra tencerenin kapağını kapatın ve kısık ateşte pirinçler suyunu çekene kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve demlenmesi için kapağını açmadan yaklaşık 10-15 dakika bekleyin.",
            // "Demlenen pilavı karıştırarak servis yapın. Afiyet olsun!"
            "nohutluTarif1",
            "nohutluTarif2",
            "nohutluTarif3",
            "nohutluTarif4",
            "nohutluTarif5",
            "nohutluTarif6",
            "nohutluTarif7",
        ],
        image: nohutluPilavImage
    },
    {
        id: 6,
        title: "Bademli Pilav",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı pirinç",
            // "1 su bardağı badem",
            // "2 yemek kaşığı tereyağı",
            // "2 yemek kaşığı sıvı yağ",
            // "3 su bardağı su veya tavuk suyu",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "1 adet küçük soğan (isteğe bağlı, ince doğranmış)"
            "bademli1",
            "bademli2",
            "bademli3",
            "bademli4",
            "bademli5",
            "bademli6",
            "bademli7",
            "bademli8",
        ],
        instructions: [
            // "Pirinçleri tuzlu ılık suda yaklaşık 20-30 dakika bekletin. Daha sonra bol su ile yıkayıp süzün.",
            // "Bademlerin kabuklarını kolayca soymak için kaynar suya batırıp birkaç dakika bekletin, ardından soğuk suya alın ve kabuklarını soyun.",
            // "Bir tencereye tereyağını ve sıvı yağı ekleyin. Yağlar eridikten sonra bademleri ekleyin ve hafifçe kavurun. (Eğer soğan kullanıyorsanız, bademlerle birlikte soğanları da ekleyin ve soğanlar pembeleşene kadar kavurun.)",
            // "Pirinçleri ekleyin ve pirinçler şeffaflaşana kadar kavurun.",
            // "Tuz ve karabiberi ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Kaynadıktan sonra tencerenin kapağını kapatın ve kısık ateşte pirinçler suyunu çekene kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve demlenmesi için kapağını açmadan yaklaşık 10-15 dakika bekleyin.",
            // "Demlenen pilavı karıştırarak servis yapın. Afiyet olsun!"
            "bademliTarif1",
            "bademliTarif2",
            "bademliTarif3",
            "bademliTarif4",
            "bademliTarif5",
            "bademliTarif6",
            "bademliTarif7",
            "bademliTarif8",
        ],
        image: bademliPilavImage
    },
    {
        id: 7,
        title: "Domatesli Pilav",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı pirinç",
            // "2 adet büyük domates (rendelenmiş)",
            // "1 adet yeşil biber (isteğe bağlı, doğranmış)",
            // "2 yemek kaşığı tereyağı",
            // "2 yemek kaşığı sıvı yağ",
            // "3 su bardağı su veya tavuk suyu",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber"
            "domatesli1",
            "domatesli2",
            "domatesli3",
            "domatesli4",
            "domatesli5",
            "domatesli6",
            "domatesli7",
            "domatesli8",
        ],
        instructions: [
            // "Pirinçleri tuzlu ılık suda yaklaşık 20-30 dakika bekletin. Daha sonra bol su ile yıkayıp süzün.",
            // "Bir tencereye tereyağını ve sıvı yağı ekleyin. Yağlar eridikten sonra doğranmış yeşil biberleri ekleyin ve hafifçe kavurun (isteğe bağlı).",
            // "Rendelenmiş domatesleri ekleyin ve domatesler suyunu çekene kadar kavurun.",
            // "Pirinçleri ekleyin ve pirinçler şeffaflaşana kadar kavurun.",
            // "Tuz ve karabiberi ekleyin, ardından suyu veya tavuk suyunu ekleyin. Karıştırarak kaynamaya bırakın.",
            // "Kaynadıktan sonra tencerenin kapağını kapatın ve kısık ateşte pirinçler suyunu çekene kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve demlenmesi için kapağını açmadan yaklaşık 10-15 dakika bekleyin.",
            // "Demlenen pilavı karıştırarak servis yapın. Afiyet olsun!"
            "domatesliTarif1",
            "domatesliTarif2",
            "domatesliTarif3",
            "domatesliTarif4",
            "domatesliTarif5",
            "domatesliTarif6",
            "domatesliTarif7",
            "domatesliTarif8",
        ],
        image: domatesliPilavImage
    },
    {
        id: 8,
        title: "Sebzeli Bulgur Pilavı",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı bulgur",
            // "1 adet büyük soğan (ince doğranmış)",
            // "1 adet yeşil biber (doğranmış)",
            // "1 adet kırmızı biber (doğranmış)",
            // "1 adet havuç (rendelenmiş)",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı tereyağı veya sıvı yağ",
            // "3 su bardağı su veya tavuk suyu",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "1 çay kaşığı pul biber (isteğe bağlı)"
            "sebzeli1",
            "sebzeli2",
            "sebzeli3",
            "sebzeli4",
            "sebzeli5",
            "sebzeli6",
            "sebzeli7",
            "sebzeli8",
            "sebzeli9",
            "sebzeli10",
            "sebzeli11",
        ],
        instructions: [
            // "Bir tencereye tereyağını veya sıvı yağı ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Doğranmış yeşil ve kırmızı biberleri ekleyin ve biberler yumuşayana kadar kavurun.",
            // "Rendelenmiş havucu ekleyin ve birkaç dakika daha kavurmaya devam edin.",
            // "Rendelenmiş domatesleri ekleyin ve domatesler suyunu çekene kadar pişirin.",
            // "Bulguru ekleyin ve bulgurlar şeffaflaşana kadar kavurun.",
            // "Tuz, karabiber ve pul biberi ekleyin. Ardından suyu veya tavuk suyunu ekleyin ve karıştırarak kaynamaya bırakın.",
            // "Kaynadıktan sonra tencerenin kapağını kapatın ve kısık ateşte bulgurlar suyunu çekene kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve demlenmesi için kapağını açmadan yaklaşık 10-15 dakika bekleyin.",
            // "Demlenen pilavı karıştırarak servis yapın. Afiyet olsun!"
            "sebzeliTarif1",
            "sebzeliTarif2",
            "sebzeliTarif3",
            "sebzeliTarif4",
            "sebzeliTarif5",
            "sebzeliTarif6",
            "sebzeliTarif7",
            "sebzeliTarif8",
            "sebzeliTarif9",
        ],
        image: sebzeliBulgurPilaviImage
    },
    {
        id: 9,
        title: "Akasya Pilavı",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı pirinç",
            // "1 su bardağı doğranmış tavuk göğsü",
            // "1 su bardağı bezelye",
            // "1 adet büyük soğan (ince doğranmış)",
            // "1 adet havuç (küp doğranmış)",
            // "2 yemek kaşığı tereyağı veya sıvı yağ",
            // "3 su bardağı su veya tavuk suyu",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "1 çay kaşığı zerdeçal (isteğe bağlı)",
            // "1 çay kaşığı kimyon (isteğe bağlı)"
            "akasya1",
            "akasya2",
            "akasya3",
            "akasya4",
            "akasya5",
            "akasya6",
            "akasya7",
            "akasya8",
            "akasya9",
            "akasya10",
            "akasya11",
        ],
        instructions: [
            // "Pirinçleri tuzlu ılık suda yaklaşık 20-30 dakika bekletin. Daha sonra bol su ile yıkayıp süzün.",
            // "Bir tencereye tereyağını veya sıvı yağı ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Doğranmış tavuk göğsünü ekleyin ve tavuklar tamamen pişene kadar kavurun.",
            // "Küp doğranmış havucu ekleyin ve birkaç dakika kavurmaya devam edin.",
            // "Bezelyeleri ekleyin ve karıştırın.",
            // "Pirinçleri ekleyin ve pirinçler şeffaflaşana kadar kavurun.",
            // "Tuz, karabiber, zerdeçal ve kimyonu ekleyin. Ardından suyu veya tavuk suyunu ekleyin ve karıştırarak kaynamaya bırakın.",
            // "Kaynadıktan sonra tencerenin kapağını kapatın ve kısık ateşte pirinçler suyunu çekene kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve demlenmesi için kapağını açmadan yaklaşık 10-15 dakika bekleyin.",
            // "Demlenen pilavı karıştırarak servis yapın. Afiyet olsun!"
            "akasyaTarif1",
            "akasyaTarif2",
            "akasyaTarif3",
            "akasyaTarif4",
            "akasyaTarif5",
            "akasyaTarif6",
            "akasyaTarif7",
            "akasyaTarif8",
            "akasyaTarif9",
            "akasyaTarif10",
        ],
        image: akasyaPilaviImage
    },
    {
        id: 10,
        title: "Etli Bulgur Pilavı",
        type: "Pilavlar",
        ingredients: [
            // "2 su bardağı bulgur",
            // "300 gram kuşbaşı doğranmış dana eti",
            // "1 büyük soğan",
            // "2 diş sarımsak",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı domates salçası",
            // "4 yemek kaşığı zeytinyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "4 su bardağı su veya et suyu",
            // "1 demet maydanoz"
            "etli1",
            "etli2",
            "etli3",
            "etli4",
            "etli5",
            "etli6",
            "etli7",
            "etli8",
            "etli9",
            "etli10",
            "etli11",
        ],
        instructions: [
            // "Kuşbaşı doğranmış eti tencereye alın ve kendi suyunu salıp çekene kadar kavurun. Ardından zeytinyağını ekleyin ve etler kızarana kadar kavurun.",
            // "İnce doğranmış soğanı ve sarımsakları ekleyin, soğanlar pembeleşene kadar kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin. Ardından rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            // "Tuzu ve karabiberi ekleyin. Bulguru ekleyin ve birkaç dakika kavurun.",
            // "Suyu veya et suyunu ekleyin ve karıştırın. Tencerenin kapağını kapatın ve kısık ateşte bulgurlar yumuşayana kadar pişirin.",
            // "Pilav piştikten sonra ocaktan alın ve ince doğranmış maydanozları ekleyin.",
            // "Etli bulgur pilavını sıcak olarak servis yapın. Afiyet olsun!"
            "etliTarif1",
            "etliTarif2",
            "etliTarif3",
            "etliTarif4",
            "etliTarif5",
            "etliTarif6",
            "etliTarif7",
        ],
        image: etliBulgurImage
    },
    {
        id: 11,
        title: "Kuru Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            // "2 su bardağı kuru fasulye",
            // "1 büyük soğan, doğranmış",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates, rendelenmiş veya küçük doğranmış",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz (miktarı damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "İsteğe bağlı olarak pul biber",
            // "Su"
            "kuru1",
            "kuru2",
            "kuru3",
            "kuru4",
            "kuru5",
            "kuru6",
            "kuru7",
            "kuru8",
            "kuru9",
        ],
        instructions: [
            // "Kuru fasulyeleri bir gece önceden bol suyla kaplı bir kapta bekletin. Eğer vakit yoksa, hızlı bir şekilde haşlayarak da kullanabilirsiniz.",
            // "Haşlanmış ve süzülmüş kuru fasulyeleri bir tencereye alın. Üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Bir tencerede sıvı yağı veya tereyağını ısıtın. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Salçayı ekleyin ve kavurmaya devam edin, ardından domatesleri ekleyin.",
            // "Baharatları ve isteğe bağlı olarak pul biberi ekleyin. Karıştırarak pişirin.",
            // "Hazırlanan bu karışımı haşlanmış fasulyelerin üzerine ekleyin ve karıştırın.",
            // "Tencerenin kapağını kapatın ve kısık ateşte fasulyeler yumuşayana kadar pişirin. Bu genellikle yaklaşık 45 dakika ile 1 saat arasında sürebilir. Ara sıra karıştırmayı unutmayın.",
            // "Fasulyeler yumuşayıp sosu kıvam alınca ocaktan alın.",
            // "Sıcak olarak pilav ve turşu ile servis yapın. Afiyet olsun!"
            "kuruTarif1",
            "kuruTarif2",
            "kuruTarif3",
            "kuruTarif4",
            "kuruTarif5",
            "kuruTarif6",
            "kuruTarif7",
            "kuruTarif8",
            "kuruTarif9",
        ],
        image: kuruFasulyeImage
    },
    {
        id: 12,
        title: "Etli Kuru Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            // "2 su bardağı kuru fasulye",
            // "300 gram kuşbaşı doğranmış dana eti",
            // "1 büyük soğan",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "Su"
            "etliKuru1",
            "etliKuru2",
            "etliKuru3",
            "etliKuru4",
            "etliKuru5",
            "etliKuru6",
            "etliKuru7",
            "etliKuru8",
            "etliKuru9",
        ],
        instructions: [
            // "Kuru fasulyeleri bir gece önceden bol suyla kaplı bir kapta bekletin. Eğer zamanınız yoksa, hızlı bir şekilde haşlayarak da kullanabilirsiniz.",
            // "Bir tencereye sıvı yağı veya tereyağını ekleyin. Kuşbaşı doğranmış dana etini ekleyip kendi suyunu salıp çekene kadar kavurun.",
            // "Kavrulan etlerin üzerine ince doğranmış soğanları ekleyin ve pembeleşene kadar kavurmaya devam edin.",
            // "Soğanlar pembeleşince domates salçasını ekleyin ve kavurmaya devam edin, ardından rendelenmiş domatesleri ekleyip karıştırın.",
            // "Tuz, karabiber ve isteğe bağlı olarak pul biberi ekleyin. Baharatlarla birlikte karıştırın ve salçanın kokusu çıkana kadar pişirin.",
            // "Önceden ıslattığınız ve süzdüğünüz kuru fasulyeleri tencereye ekleyin. Üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Tencerenin kapağını kapatın ve kısık ateşte fasulyeler yumuşayana kadar pişirin. Bu süre genellikle 45 dakika ile 1 saat arasında değişebilir. Ara sıra karıştırmayı unutmayın.",
            // "Etli kuru fasulye piştikten sonra ocaktan alın ve birkaç dakika dinlendirin.",
            // "Sıcak olarak pilav ve turşu ile servis yapın. Afiyet olsun!"
            "etliKuruTarif1",
            "etliKuruTarif2",
            "etliKuruTarif3",
            "etliKuruTarif4",
            "etliKuruTarif5",
            "etliKuruTarif6",
            "etliKuruTarif7",
            "etliKuruTarif8",
            "etliKuruTarif9",
        ],
        image: etliKuruFasulyeImage
    },
    {
        id: 13,
        title: "Güveçte Şeker Fasulye",
        type: "Fasulye Yemekleri",
        ingredients: [
            // "500 gram şeker fasulye",
            // "2 orta boy domates, rendelenmiş veya küçük doğranmış",
            // "1 büyük soğan, doğranmış",
            // "2 yemek kaşığı sıvı yağ veya zeytinyağı",
            // "1 tatlı kaşığı tuz (damak zevkinize göre ayarlayabilirsiniz)",
            // "1 çay kaşığı karabiber",
            // "1 çay kaşığı toz şeker",
            // "1 su bardağı sıcak su"
            "guvec1",
            "guvec2",
            "guvec3",
            "guvec4",
            "guvec5",
            "guvec6",
            "guvec7",
            "guvec8",
        ],
        instructions: [
            // "Şeker fasulyelerini yıkayın ve süzün.",
            // "Bir güveç veya derin bir tencereye sıvı yağı ekleyin. Doğranmış soğanları ekleyip pembeleşene kadar kavurun.",
            // "Rendelenmiş veya doğranmış domatesleri ekleyin, karıştırarak pişirin.",
            // "Baharatları (tuz, karabiber, toz şeker) ekleyin ve karıştırın.",
            // "Hazırlanan sosun üzerine yıkanmış şeker fasulyelerini ekleyin.",
            // "Sıcak suyu ekleyin, karıştırın ve güvecin kapağını kapatın.",
            // "Önceden ısıtılmış 180°C fırında yaklaşık 45-60 dakika pişirin, fasulyeler yumuşayana kadar. Arada bir kontrol ederek gerektiğinde su ekleyebilirsiniz.",
            // "Pişen güveçte şeker fasulyeyi fırından çıkarın ve servis yapmadan önce birkaç dakika dinlendirin.",
            // "Sıcak olarak servis yapın. Afiyet olsun!"
            "guvecTarif1",
            "guvecTarif2",
            "guvecTarif3",
            "guvecTarif4",
            "guvecTarif5",
            "guvecTarif6",
            "guvecTarif7",
            "guvecTarif8",
            "guvecTarif9",
        ],
        image: sekerFasulyeImage
    },
    {
        id: 14,
        title: "Beyaz Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            // "2 su bardağı nohut",
            // "1 büyük soğan",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "Su",
            // "İsteğe bağlı: 1 tatlı kaşığı pul biber, 1 tatlı kaşığı kimyon"
            "beyaz1",
            "beyaz2",
            "beyaz3",
            "beyaz4",
            "beyaz",
            "beyaz61",
            "beyaz7",
            "beyaz8",
            "beyaz9",
        ],
        instructions: [
            // "Nohutları bir gece önceden suya koyun ve sabaha kadar bekletin. Eğer vakit yoksa, hızlı bir şekilde haşlayarak da bu işlemi yapabilirsiniz.",
            // "Bir tencereye sıvı yağ veya tereyağını ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin.",
            // "Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            // "Tuz, karabiber ve isteğe bağlı olarak pul biber ve kimyonu ekleyin.",
            // "Önceden ıslatılmış ve suyu süzülmüş nohutları tencereye ekleyin.",
            // "Nohutların üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Tencerenin kapağını kapatın ve kısık ateşte nohutlar yumuşayana kadar pişirin. Bu yaklaşık 45 dakika ile 1 saat arasında sürebilir. Ara sıra karıştırmayı unutmayın.",
            // "Nohutlar yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            // "Sıcak olarak servis yapın. Afiyet olsun!"
            "beyazTarif1",
            "beyazTarif2",
            "beyazTarif3",
            "beyazTarif4",
            "beyazTarif5",
            "beyazTarif6",
            "beyazTarif7",
            "beyazTarif8",
            "beyazTarif9",
            "beyazTarif10",
        ],
        image: beyazNohutImage
    },
    {
        id: 15,
        title: "Tavuklu Beyaz Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            // "2 su bardağı nohut",
            // "300 gram tavuk göğsü (kuşbaşı doğranmış)",
            // "1 büyük soğan",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "Su",
            // "İsteğe bağlı: 1 tatlı kaşığı pul biber, 1 tatlı kaşığı kimyon"
            "tavuklu1",
            "tavuklu2",
            "tavuklu3",
            "tavuklu4",
            "tavuklu5",
            "tavuklu6",
            "tavuklu7",
            "tavuklu8",
            "tavuklu9",
            "tavuklu10",
        ],
        instructions: [
            // "Nohutları bir gece önceden suya koyun ve sabaha kadar bekletin. Eğer vakit yoksa, hızlı bir şekilde haşlayarak da bu işlemi yapabilirsiniz.",
            // "Bir tencereye sıvı yağ veya tereyağını ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Kuşbaşı doğranmış tavuk göğsünü ekleyin ve tavuklar tamamen pişene kadar kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin.",
            // "Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            // "Tuz, karabiber ve isteğe bağlı olarak pul biber ve kimyonu ekleyin.",
            // "Önceden ıslatılmış ve suyu süzülmüş nohutları tencereye ekleyin.",
            // "Nohutların üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Tencerenin kapağını kapatın ve kısık ateşte nohutlar ve tavuklar yumuşayana kadar pişirin. Bu yaklaşık 45 dakika ile 1 saat arasında sürebilir. Ara sıra karıştırmayı unutmayın.",
            // "Nohutlar ve tavuklar yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            // "Sıcak olarak servis yapın. Afiyet olsun!"
            "tavukluTarif1",
            "tavukluTarif2",
            "tavukluTarif3",
            "tavukluTarif4",
            "tavukluTarif5",
            "tavukluTarif6",
            "tavukluTarif7",
            "tavukluTarif8",
            "tavukluTarif9",
            "tavukluTarif10",
            "tavukluTarif11",
        ],
        image: tavukluBeyazNohutImage
    },
    {
        id: 16,
        title: "Koçbaşı Nohut",
        type: "Nohut Yemekleri",
        ingredients: [
            // "2 su bardağı koçbaşı nohut",
            // "1 büyük soğan",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "Su",
            // "İsteğe bağlı: 1 tatlı kaşığı pul biber, 1 tatlı kaşığı kimyon"
            "kocbasi1",
            "kocbasi2",
            "kocbasi3",
            "kocbasi4",
            "kocbasi5",
            "kocbasi6",
            "kocbasi7",
            "kocbasi8",
            "kocbasi9",
        ],
        instructions: [
            // "Nohutları bir gece önceden suya koyun ve sabaha kadar bekletin. Eğer vakit yoksa, hızlı bir şekilde haşlayarak da bu işlemi yapabilirsiniz.",
            // "Bir tencereye sıvı yağ veya tereyağını ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin.",
            // "Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            // "Tuz, karabiber ve isteğe bağlı olarak pul biber ve kimyonu ekleyin.",
            // "Önceden ıslatılmış ve suyu süzülmüş nohutları tencereye ekleyin.",
            // "Nohutların üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Tencerenin kapağını kapatın ve kısık ateşte nohutlar yumuşayana kadar pişirin. Bu yaklaşık 45 dakika ile 1 saat arasında sürebilir. Ara sıra karıştırmayı unutmayın.",
            // "Nohutlar yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            // "Sıcak olarak servis yapın. Afiyet olsun!"
            "kocbasiTarif1",
            "kocbasiTarif2",
            "kocbasiTarif3",
            "kocbasiTarif4",
            "kocbasiTarif5",
            "kocbasiTarif6",
            "kocbasiTarif7",
            "kocbasiTarif8",
            "kocbasiTarif9",
            "kocbasiTarif10",
        ],
        image: kocbasiNohutImage
    },
    {
        id: 17,
        title: "Nohut Güveç",
        type: "Nohut Yemekleri",
        ingredients: [
            // "2 su bardağı nohut",
            // "300 gram kuşbaşı doğranmış kuzu eti",
            // "1 büyük soğan",
            // "2 yemek kaşığı domates salçası",
            // "2 adet domates (rendelenmiş)",
            // "2 yemek kaşığı sıvı yağ veya tereyağı",
            // "1 tatlı kaşığı tuz",
            // "1 çay kaşığı karabiber",
            // "1 tatlı kaşığı pul biber (isteğe bağlı)",
            // "1 tatlı kaşığı kimyon (isteğe bağlı)",
            // "Su"
            "nohut1",
            "nohut2",
            "nohut3",
            "nohut4",
            "nohut5",
            "nohut6",
            "nohut7",
            "nohut8",
            "nohut9",
            "nohut10",
            "nohut11",
        ],
        instructions: [
            // "Nohutları bir gece önceden suya koyun ve sabaha kadar bekletin. Eğer vakit yoksa, hızlı bir şekilde haşlayarak da bu işlemi yapabilirsiniz.",
            // "Bir güveç tenceresinde sıvı yağ veya tereyağını ısıtın. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            // "Kuşbaşı doğranmış kuzu etini ekleyin ve etler tamamen pişene kadar kavurun.",
            // "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin.",
            // "Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            // "Tuz, karabiber ve isteğe bağlı olarak pul biber ve kimyonu ekleyin.",
            // "Önceden ıslatılmış ve suyu süzülmüş nohutları güveç tenceresine ekleyin.",
            // "Nohutların üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            // "Güveç tenceresinin kapağını kapatın ve kısık ateşte nohutlar ve etler yumuşayana kadar pişirin. Bu yaklaşık 1 saat sürebilir. Ara sıra karıştırmayı unutmayın.",
            // "Nohutlar ve etler yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            // "Sıcak olarak servis yapın. Afiyet olsun!"
            "nohutTarif1",
            "nohutTarif2",
            "nohutTarif3",
            "nohutTarif4",
            "nohutTarif5",
            "nohutTarif6",
            "nohutTarif7",
            "nohutTarif8",
            "nohutTarif9",
            "nohutTarif10",
            "nohutTarif11",
        ],
        image: nohutGuvecImage
    },
    {
        id: 18,
        title: "Yeşil Mercimek",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "2 su bardağı yeşil mercimek",
            "1 büyük soğan",
            "2 diş sarımsak",
            "2 yemek kaşığı domates salçası",
            "2 adet domates (rendelenmiş)",
            "2 yemek kaşığı sıvı yağ veya tereyağı",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 tatlı kaşığı pul biber (isteğe bağlı)",
            "1 tatlı kaşığı kimyon (isteğe bağlı)",
            "Su"
        ],
        instructions: [
            "Yeşil mercimekleri yıkayın ve bir tencereye alın. Üzerini geçecek kadar su ekleyin ve kaynatın. Kaynadıktan sonra suyunu süzün ve mercimekleri bir kenara alın.",
            "Bir tencereye sıvı yağ veya tereyağını ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            "Sarımsakları ekleyin ve birkaç dakika daha kavurun.",
            "Domates salçasını ekleyin ve kokusu çıkana kadar kavurmaya devam edin.",
            "Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            "Tuz, karabiber ve isteğe bağlı olarak pul biber ve kimyonu ekleyin.",
            "Haşlanmış yeşil mercimekleri tencereye ekleyin ve karıştırın.",
            "Mercimeklerin üzerini geçecek kadar sıcak su ekleyin ve karıştırın.",
            "Tencerenin kapağını kapatın ve kısık ateşte mercimekler yumuşayana kadar pişirin. Bu yaklaşık 30-40 dakika sürebilir. Ara sıra karıştırmayı unutmayın.",
            "Yeşil mercimekler yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            "Sıcak olarak servis yapın. Afiyet olsun!"
        ],
        image: yesilMercimekImage
    },
    {
        id: 19,
        title: "Yeşil Mercimekli Ispanak",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "1 su bardağı yeşil mercimek",
            "500 gram ıspanak",
            "1 büyük soğan",
            "2 diş sarımsak",
            "2 yemek kaşığı domates salçası",
            "1 yemek kaşığı biber salçası (isteğe bağlı)",
            "3 yemek kaşığı sıvı yağ",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 tatlı kaşığı kırmızı biber",
            "Su"
        ],
        instructions: [
            "Yeşil mercimekleri yıkayın ve bir tencereye alın. Üzerini geçecek kadar su ekleyin ve kaynatın. Kaynadıktan sonra suyunu süzün ve mercimekleri bir kenara alın.",
            "Ispanakları iyice yıkayın ve doğrayın.",
            "Bir tencereye sıvı yağı ekleyin. Yağ ısındıktan sonra ince doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            "Sarımsakları ekleyin ve birkaç dakika daha kavurun.",
            "Domates salçasını ve biber salçasını ekleyin, kokusu çıkana kadar kavurmaya devam edin.",
            "Yeşil mercimekleri tencereye ekleyin ve karıştırın.",
            "Doğranmış ıspanakları ekleyin ve karıştırarak pişirin.",
            "Tuz, karabiber ve kırmızı biberi ekleyin.",
            "Yemek suyunu çektikçe azar azar sıcak su ekleyin. Ispanaklar ve mercimekler iyice pişene kadar kısık ateşte pişirin.",
            "Yeşil mercimekler ve ıspanaklar yumuşadıktan sonra ocaktan alın ve bir süre dinlendirin.",
            "Sıcak olarak servis yapın. Afiyet olsun!"
        ],
        image: yesilMercimekliIspanakImage
    },
    {
        id: 20,
        title: "Yeşil Mercimek Köftesi",
        type: "Yeşil Mercimek Yemekleri",
        ingredients: [
            "1 su bardağı yeşil mercimek",
            "1 su bardağı ince bulgur",
            "1 büyük soğan",
            "2 diş sarımsak",
            "2 yemek kaşığı domates salçası",
            "2 yemek kaşığı biber salçası",
            "3 yemek kaşığı sıvı yağ",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 çay kaşığı kimyon",
            "1 çay kaşığı kırmızı biber",
            "Yarım demet maydanoz",
            "3-4 dal taze soğan",
            "1 limonun suyu",
            "Su"
        ],
        instructions: [
            "Yeşil mercimekleri yıkayın ve bir tencereye alın. Üzerini geçecek kadar su ekleyin ve yumuşayana kadar haşlayın. Haşladıktan sonra suyunu süzün ve bir kenara alın.",
            "Bir kaba ince bulguru alın ve üzerine 1 su bardağı sıcak su ekleyin. Bulgurun şişmesi için 10 dakika bekletin.",
            "Bir tavada sıvı yağı ısıtın. İnce doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            "Sarımsakları ekleyin ve birkaç dakika daha kavurun.",
            "Domates salçası ve biber salçasını ekleyin, kokusu çıkana kadar kavurmaya devam edin.",
            "Haşlanmış yeşil mercimekleri ekleyin ve karıştırın. Tuzu, karabiberi, kimyonu ve kırmızı biberi ekleyin.",
            "Bu karışımı şişen bulgura ekleyin ve iyice karıştırın.",
            "İnce doğranmış maydanoz ve taze soğanları ekleyin. Limon suyunu ekleyin ve tüm malzemeleri iyice karıştırın.",
            "Ellerinizi hafifçe ıslatarak karışımdan küçük parçalar alın ve köfte şekli verin.",
            "Hazırladığınız yeşil mercimek köftelerini servis tabağına alın.",
            "Afiyet olsun!"
        ],
        image: yesilMercimekKoftesiImage
    },
    {
        id: 21,
        title: "Barbunya Pilaki",
        type: "Barbunya Yemekleri",
        ingredients: [
            "2 su bardağı barbunya",
            "1 büyük soğan",
            "2 diş sarımsak",
            "2 adet havuç",
            "2 adet patates",
            "2 adet domates (rendelenmiş)",
            "2 yemek kaşığı domates salçası",
            "4 yemek kaşığı zeytinyağı",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 tatlı kaşığı toz şeker",
            "1 demet maydanoz",
            "Su"
        ],
        instructions: [
            "Barbunyaları bir gece önceden suya koyun ve sabaha kadar bekletin. Beklettikten sonra suyunu süzün ve temiz su ile haşlayın. Haşlandıktan sonra suyunu süzün ve bir kenara alın.",
            "Bir tencereye zeytinyağını ekleyin ve ısıtın. İnce doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            "Sarımsakları ekleyin ve birkaç dakika daha kavurun.",
            "Doğranmış havuçları ekleyin ve birkaç dakika kavurun. Ardından küp doğranmış patatesleri ekleyin ve karıştırarak kavurmaya devam edin.",
            "Domates salçasını ekleyin ve kokusu çıkana kadar kavurun. Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            "Haşlanmış barbunyaları ekleyin ve karıştırın. Tuzu, karabiberi ve toz şekeri ekleyin.",
            "Tencereye barbunyaların üzerini geçecek kadar sıcak su ekleyin. Tencerenin kapağını kapatın ve kısık ateşte barbunyalar yumuşayana kadar pişirin.",
            "Yemeğiniz piştikten sonra ocaktan alın ve ince doğranmış maydanozları ekleyin.",
            "Barbunya pilakiyi ılık veya soğuk olarak servis yapın. Afiyet olsun!"
        ],
        image: barbunyaPilakiImage
    },
    {
        id: 22,
        title: "Kiraz Barbunya",
        type: "Barbunya Yemekleri",
        ingredients: [
            "2 su bardağı kiraz barbunya",
            "1 büyük soğan",
            "2 diş sarımsak",
            "2 adet havuç",
            "2 adet patates",
            "2 adet domates (rendelenmiş)",
            "2 yemek kaşığı domates salçası",
            "4 yemek kaşığı zeytinyağı",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 tatlı kaşığı toz şeker",
            "1 demet maydanoz",
            "Su"
        ],
        instructions: [
            "Kiraz barbunyaları bir gece önceden suya koyun ve sabaha kadar bekletin. Beklettikten sonra suyunu süzün ve temiz su ile haşlayın. Haşlandıktan sonra suyunu süzün ve bir kenara alın.",
            "Bir tencereye zeytinyağını ekleyin ve ısıtın. İnce doğranmış soğanı ekleyin ve pembeleşene kadar kavurun.",
            "Sarımsakları ekleyin ve birkaç dakika daha kavurun.",
            "Doğranmış havuçları ekleyin ve birkaç dakika kavurun. Ardından küp doğranmış patatesleri ekleyin ve karıştırarak kavurmaya devam edin.",
            "Domates salçasını ekleyin ve kokusu çıkana kadar kavurun. Rendelenmiş domatesleri ekleyin ve karıştırarak pişirin.",
            "Haşlanmış kiraz barbunyaları ekleyin ve karıştırın. Tuzu, karabiberi ve toz şekeri ekleyin.",
            "Tencereye barbunyaların üzerini geçecek kadar sıcak su ekleyin. Tencerenin kapağını kapatın ve kısık ateşte barbunyalar yumuşayana kadar pişirin.",
            "Yemeğiniz piştikten sonra ocaktan alın ve ince doğranmış maydanozları ekleyin.",
            "Kiraz barbunyayı ılık veya soğuk olarak servis yapın. Afiyet olsun!"
        ],
        image: kirazBarbunyaImage
    },
    {
        id: 23,
        title: "Bulgurlu Köfte",
        type: "Diğer Yemekler",
        ingredients: [
            "1 su bardağı ince bulgur",
            "250 gram kıyma",
            "1 büyük soğan",
            "1 yumurta",
            "2 yemek kaşığı domates salçası",
            "1 yemek kaşığı biber salçası",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı karabiber",
            "1 çay kaşığı kimyon",
            "1 demet maydanoz",
            "4 yemek kaşığı zeytinyağı",
            "1 su bardağı sıcak su"
        ],
        instructions: [
            "İnce bulguru geniş bir kaba alın ve üzerine sıcak suyu ekleyin. Üstünü kapatıp bulgurların şişmesi için 10-15 dakika bekletin.",
            "Şişen bulgura kıymayı ekleyin. İnce doğranmış soğanı, yumurtayı, domates salçasını, biber salçasını, tuzu, karabiberi ve kimyonu ekleyin.",
            "Karışımı yoğurarak köfte harcını hazırlayın. Harçtan küçük parçalar koparıp yuvarlayarak köfteleri şekillendirin.",
            "Bir tavada zeytinyağını ısıtın ve köfteleri her iki tarafı da kızarana kadar pişirin.",
            "Pişen köfteleri servis tabağına alın ve üzerine ince doğranmış maydanozu serpin.",
            "Bulgurlu köfteleri sıcak olarak servis yapın. Afiyet olsun!"
        ],
        image: bulgurluKofteImage
    },
    {
        id: 24,
        title: "Yaprak Sarma",
        type: "Diğer Yemekler",
        ingredients: [
            "500 gram asma yaprağı",
            "2 su bardağı pirinç",
            "2 büyük soğan",
            "1 demet maydanoz",
            "1 demet dereotu",
            "1 tatlı kaşığı kuru nane",
            "1 tatlı kaşığı karabiber",
            "1 tatlı kaşığı tuz",
            "1 çay kaşığı tarçın",
            "1 çay bardağı zeytinyağı",
            "2 yemek kaşığı domates salçası",
            "1 limon",
            "2 su bardağı su"
        ],
        instructions: [
            "Asma yapraklarını kaynar suya batırarak 1-2 dakika haşlayın ve süzgeçte süzülmeye bırakın.",
            "Pirinçleri yıkayıp süzün. Soğanları ince doğrayın ve zeytinyağında kavurun. Pirinçleri ekleyip 2-3 dakika kavurun.",
            "Doğranmış maydanoz, dereotu, kuru nane, karabiber, tuz ve tarçını ekleyin. Domates salçasını ekleyin ve karıştırın.",
            "Karışımı ocaktan alın ve biraz soğumaya bırakın.",
            "Her bir yaprağın orta kısmına hazırladığınız iç harçtan bir miktar koyun ve yaprakları sıkıca sarın.",
            "Sardığınız yaprakları tencereye dizin. Üzerine limon dilimleri yerleştirin ve 2 su bardağı suyu ekleyin.",
            "Yaprakların üzerine bir tabak kapatın ve tencerenin kapağını kapatın. Kısık ateşte yaklaşık 45 dakika pişirin.",
            "Pişen yaprak sarmaları soğumaya bırakın ve servis yapın. Afiyet olsun!"
        ],
        image: yaprakSarmaImage
    },
    {
        id: 25,
        title: "Yalancı Çiğ Köfte",
        type: "Diğer Yemekler",
        ingredients: [
            "2 su bardağı ince bulgur",
            "1.5 su bardağı sıcak su",
            "1 büyük soğan",
            "2 diş sarımsak",
            "3 yemek kaşığı domates salçası",
            "2 yemek kaşığı biber salçası",
            "1 çay bardağı zeytinyağı",
            "1 tatlı kaşığı tuz",
            "1 tatlı kaşığı kimyon",
            "1 tatlı kaşığı karabiber",
            "1 tatlı kaşığı pul biber",
            "1 tatlı kaşığı isot",
            "1 demet maydanoz",
            "4-5 dal taze soğan",
            "1 limonun suyu",
            "Marul ve limon dilimleri (servis için)"
        ],
        instructions: [
            "Bulguru geniş bir kaba alın ve üzerine sıcak suyu ekleyin. Üstünü kapatıp bulgurların şişmesi için 10-15 dakika bekletin.",
            "Soğanı ve sarımsağı rendeleyin. Şişen bulgura ekleyin.",
            "Domates salçası, biber salçası, zeytinyağı, tuz, kimyon, karabiber, pul biber ve isotu ekleyin. İyice yoğurun.",
            "Doğranmış maydanoz ve taze soğanı ekleyin. Limon suyunu ekleyin ve yoğurmaya devam edin.",
            "Karışımdan küçük parçalar koparıp elinizle şekil verin.",
            "Yalancı çiğ köfteleri marul yaprakları ve limon dilimleri ile servis edin. Afiyet olsun!"
        ],
        image: yalanciCigKofteImage
    },
    {
        id: 26,
        title: "Aşure",
        type: "Diğer Yemekler",
        ingredients: [
            "2 su bardağı buğday",
            "1 su bardağı nohut",
            "1 su bardağı kuru fasulye",
            "1 su bardağı kuru kayısı",
            "1 su bardağı kuru incir",
            "1 su bardağı kuru üzüm",
            "2 su bardağı toz şeker",
            "1 su bardağı süt",
            "1 portakalın rendelenmiş kabuğu",
            "1 çay bardağı fındık",
            "1 çay bardağı ceviz",
            "1 çay bardağı badem",
            "2 litre su",
            "Nar taneleri (süsleme için)",
            "Tarçın (süsleme için)"
        ],
        instructions: [
            "Buğdayı yıkayıp büyük bir tencereye alın. Üzerini geçecek kadar su ekleyin ve bir gece bekletin.",
            "Nohut ve kuru fasulyeyi ayrı kaplarda bir gece suda bekletin. Ertesi gün nohut ve kuru fasulyeyi ayrı ayrı haşlayın.",
            "Buğdayı beklettiğiniz suyu süzün ve tencereye tekrar su ekleyip buğdayı haşlayın.",
            "Kuru kayısı, kuru incir ve kuru üzümleri küçük küçük doğrayın ve sıcak suda bekletin.",
            "Haşlanmış buğdaya haşlanmış nohut ve kuru fasulyeyi ekleyin. Suyu ekleyip karıştırın.",
            "Karışıma doğranmış kayısı, incir ve üzümleri ekleyin. Şekeri ekleyin ve karıştırın.",
            "Sütü ekleyin ve karışımı kısık ateşte kaynatmaya devam edin.",
            "Portakal kabuğu rendesi, fındık, ceviz ve bademi ekleyin. Karıştırarak birkaç dakika daha kaynatın.",
            "Aşureyi kaselere paylaştırın ve üzerini nar taneleri ve tarçın ile süsleyin.",
            "Aşureyi soğutarak servis edin. Afiyet olsun!"
        ],
        image: asureImage
    }
]

export const categories = [
    {
        id: 1,
        name: "Çorbalar",
        image: sariMercimekCorbasiImage
    },
    {
        id: 2,
        name: "Pilavlar",
        image: domatesliPilavImage
    },
    {
        id: 3,
        name: "Fasulye Yemekleri",
        image: kuruFasulyeImage
    },
    {
        id: 4,
        name: "Nohut Yemekleri",
        image: nohutGuvecImage
    },
    {
        id: 5,
        name: "Yeşil Mercimek Yemekleri",
        image: yesilMercimekImage
    },
    {
        id: 6,
        name: "Barbunya Yemekleri",
        image: barbunyaPilakiImage
    },
    {
        id: 7,
        name: "Diğer Yemekler",
        image: asureImage
    }
]